obstacle_range: 1.5 # obstacle_range < raytrace_range 
raytrace_range: 2.0 # try to increse
footprint: [[-0.55, -0.25], [-0.55, 0.25], [0.55, 0.25], [0.55, -0.25]] # [[-0.25, -0.145], [-0.25, 0.145], [0.25, 0.145], [0.25, -0.145]]
footprint_padding: 0.05 #!!!

# robot_base_frame:  base_link #base_link
transform_tolerance: 1.0 ##~~~0.5   # between base_link -> body -> odom -> map  max = 0.133463
resolution: 0.5 # ! maybe smaller 
#update_frequency: 4.0 # !! check these
#publish_frequency: 3.0 # !! check these

static_map_layer:
    map_topic: /map # /projected_map   #map
    subscribe_to_updates: true

2d_obstacles_layer:
  enabled: true
  observation_sources: scan
  scan: {data_type: LaserScan,
    expected_update_rate: 10.0,  # dont know if this is actually needed 
    topic: scan,
    inf_is_valid: true,   # why dosent work in voxel layer 
    #min_obstacle_height: 0.1,  
    #max_obstacle_height: 1.6, 
    marking: true,
    clearing: true}

3d_obstacles_layer: 
  # Voxel parameters to voxel layer 
  enabled: true
  origin_z: 0.01 #0.38 #0.01 # DONT CHANGE BETWEEN SLAM AND NAVIGATION   # gave The origin for the sensor at (0.33, -3.50, 0.03) is out of map bounds when set to 0.3
  z_resolution: 0.4
  z_voxels: 1
  publish_voxel_map: false

  observation_sources: combined_cloud left right
  combined_cloud: {data_type: PointCloud2,
    topic: /combined_cloud,   
    marking: true,
    clearing: true,
    min_obstacle_height: 0.1,  
    max_obstacle_height: 1.6, 
    expected_update_rate: 7.0,
    observation_persistence: 0.0}
  left: {data_type: PointCloud2,
    topic: /spot/depth/frontleft/cloud,   
    marking: true,
    clearing: true,
    min_obstacle_height: -0.3,   ### 0.1 
    max_obstacle_height: 1.6, 
    expected_update_rate: 7.0,
    observation_persistence: 0.0}
  right: {data_type: PointCloud2,
    topic: /spot/depth/frontright/cloud,   
    marking: true,                # For clearing obstacles 
    clearing: true,               # For clearing obstacles 
    min_obstacle_height: -0.3,    
    max_obstacle_height: 1.6, 
    expected_update_rate: 7.0,
    observation_persistence: 0.0  # For clearing obstacles 
    }
  

inflation_layer:
    inflation_radius: 0.5   # chek with 0.3
    cost_scaling_factor: 6   #10 # 2.0  maximum distance from obstacles at which a cost should be incurred


