base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS

shutdown_costmaps: false

controller_frequency: 14.0 ##14.0 #12.0 
controller_patience: 15.0 ##5 #3.0      

planner_frequency: 0.0 ##0.5 #every 2s   
planner_patience: 5.0           

oscillation_timeout: 10.0       
oscillation_distance: 0.2       

conservative_reset_dist: 0.1   


# Recovery behavior to clear costmap when it is stuck
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 0.1
  layer_names: ['2d_obstacles_layer', '3d_obstacles_layer']

aggressive_reset:
  reset_distance: 0.0
  layer_names: ['2d_obstacles_layer', '3d_obstacles_layer']
