rosplan_demo_waypoints:
    waypoint_frameid: map
    home: [1.0, -1.0, -0.0]
    wp11: [-1.5, 0.5, -0.0]
    wp12: [0.5, 7.0, 0.0]
rosplan_waypoints_goal_tolerance:
    home: [0.01, 3.62]
    wp11: [0.01, 3.62]
    wp12: [0.01, 3.62]
