rosplan_demo_waypoints:
    waypoint_frameid: map
    home: [1.0, -1.0, -0.0]
    wp21: [1.0, -1.0, -0.0]
    wp22: [-2.5, 2.0, 0.0]
    wp23: [2.5, 6.0, 0.0]
rosplan_waypoints_goal_tolerance:
    home: [0.01, 3.62]
    wp21: [0.01, 3.62]
    wp22: [0.01, 3.62]
    wp23: [0.01, 3.62]
