rosplan_demo_waypoints:
    waypoint_frameid: map
    home: [1.0, 4.0, 0.0]
    wp11: [-1.5, 4.5, 0.0]
    wp12: [1.0, 4.0, 0.0] #home
    wp13: [2.0, 5.5, 0.0]
    wp14: [1.0, 0.0, 0.0] 
    wp15: [1.5, -4.5, 0.0]
    wp_door1: [3.0, -1.5, 0.0] #robot look the door
rosplan_waypoints_goal_tolerance: # xy_goal_tolerance , yaw_goal_tolerance 
    home: [0.01, 3.62]
    wp11: [0.01, 3.62]
    wp12: [0.01, 3.62]
    wp13: [0.01, 3.62]
    wp14: [0.01, 3.62]
    wp15: [0.01, 3.62]
    wp_door1: [0.01, 0.524] #pi/6